language: python
os: linux
install: skip
jobs:
  include:
    - stage: check_release_steps
      scrips: "./.travis/check_release_step.sh"
    - stage: build
      script: "./.travis/build.sh"
      artifacts:
        paths:
          - dist/gs_api_client-$(python setup.py --version).tar.gz
    - stage: test_package
      script: "./.travis/test_sdist_package.sh"
