language: python
os: linux

install: skip
jobs:
  include:
    - stage: check_release_steps
      script: "./.travis/check_release_step.sh"
    - stage: build
      script:
        - python setup.py sdist bdist
    - stage: test-install-src
      script:
        - python setup.py sdist
        - pip install dist/gs_api_client-$(python setup.py --version).tar.gz
    - stage: test-install-wheel
      script:
        - python setup.py bdist
        - pip install dist/gs_api_client-$(python setup.py --version)-py3-none-any.whl
    - stage: test_unittest
      script: "./.travis/test_unittest.sh"
    - stage: upload_to_pypi_org
      script: "./.travis/upload_to_apipy_org.sh"

