language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

jobs:
  include:
    - stage: check_release_steps
      script: if git tag | grep -qE "^v$(python setup.py --version)$"; then echo "Release already exists"; exit 1; fi
      script: if ! grep -q "v$(python setup.py --version)" CHANGELOG.md; then echo "Version missing in CHANGELOG.md"; exit 1; fi


