language: python
os: linux
jobs:
  include:
    - stage: check_release_steps
      scrips: "./.travis/check_release_step.sh"
    - stage: build
      script: "./.travis/build.sh"
    - stage: test_package
      script: "./.travis/test_sdist_package.sh"
