language: python
os: linux

install: skip
jobs:
  include:
    - stage: check_release_steps
      script: "./.travis/check_release_step.sh"
    - stage: build
      script: "./.travis/build.sh"
    - stage: test_sdist_package
      script:
      - ./.travis/build.sh
      - ./.travis/test_sdist_package.sh
    - stage: test_bdist_wheel_package
      script:
      - ./.travis/build.sh
      - ./.travis/test_sdist_wheel_package.sh
    - stage: test_unittest
      script: "./.travis/test_unittest.sh"
    - stage: upload_to_pypi_org
      script: "./.travis/upload_to_apipy_org.sh"

