language: python

python:
  -- "3.6"
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  -
os: linux

jobs:
  include:
    - stage: check_release_steps
      scrips: "./.travis/check_release_step.sh"
    - stage: build
      script: "./.travis/build.sh"
    - stage: test_package
      script: "./.travis/test_sdist_package.sh"
