language: python
os: linux

install: skip
jobs:
  include:
    - stage: check_release_steps
      script: "./.travis/check_release_step.sh"
    - stage: build
      script: "./.travis/build.sh"
    - stage: test_package
      script:
      - ./.travis/build.sh
      - ./.travis/test_sdist_package.sh
